version: "3.8"
services:
  db:
    image: postgres:13.2-alpine
    environment:
      # Forward vars from .env so they're available when first building the container
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DB: "${POSTGRES_DB}"
    ports:
      - "5432:5432"

  backend:
    image: node:14.7.0-alpine
    user: ${UID:-1000}:${GID:-1000}
    environment:
      POSTGRES_CONNECTION_STRING: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}"
    working_dir: /app-backend
    volumes:
      - .:/app-backend
    depends_on:
      - db
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    command: npm run start:dev

  frontend:
    image: node:14.7.0-alpine
    user: ${UID:-1000}:${GID:-1000}
    working_dir: /app-frontend
    volumes:
      - ../instrument-catalog-frontend:/app-frontend
    ports:
      - "${FRONTEND_DEVSERVER_PORT:-5000}:${FRONTEND_DEVSERVER_PORT:-5000}"
    command: npm run start
