version: "3.8"
services:
  backend:
    image: node:14.7.0-alpine
    env_file: ./.env
    user: ${UID:-1000}:${GID:-1000}
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "${PORT}:${PORT}"
    command: npm start:dev
