name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  NODE_ENV: "development"
  ACCESS_CONTROL_ALLOW_ORIGIN: "http://localhost:5000"

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x outside docker containers
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Print run info
        run: |
          echo "GitHub event: $GITHUB_EVENT_NAME"
          echo "outer node version: $(node --version)"
          echo "outer npm version: $(npm --version)"
      - name: Set UID and GID environment variables
        # Our Docker Compose file will use these values for the container's user
        run: |
          echo "UID=$(id -u)" >> $GITHUB_ENV
          echo "GID=$(id -g)" >> $GITHUB_ENV
      - name: Install dependencies
        run: npm ci
      - name: Start the server
        run: docker-compose up backend -d
      - run: docker-compose exec backend npm run lint:lint
      - run: docker-compose exec backend npm run lint:types
      - run: docker-compose exec backend npm run lint:format
      - run: docker-compose exec backend npm run test:within-docker
        # Right now, we're just making sure the build doesn't fail, but later we
        # might switch to running tests directly on the JavaScript output
      - run: docker-compose exec backend npm run build
      - run: docker-compose down
